### PR TITLE
Add option to list all triggers in the tenant

### PR DESCRIPTION
**Pull request by dkorn**
Relevant for both triggers and group triggers, differ in 'type' attribute.

### CODE REVIEW

**Comment by dkorn** [comment]
@cben @enoodle @kwoodson @ivanhorvath @simon3z please review

**Comment by dkorn** [comment]
@cben can you take a look?

**Comment by cben** [comment]
> Relevant for both triggers and group triggers, differ in 'type' attribute.

Can you explain where is this `type`?  Does it list both groups & members, telling you which is which?  Or do you tell it which you want?
Can you give an example output?  And consider adding an example playbook.  It's not very clear which params you need in `list` mode.

Will/should this include associated conditions?

Ideally, the output should be similar to something you can feed back into this module.
For example might(?) want to reverse context.name and trigger_mode transformations you do in #9.
:+1: to merge as is and revisit after the group trigger format is settled...

**Comment by dkorn** [comment]
> Can you explain where is this type? Does it list both groups & members, telling you which is which? Or do you tell it which you want?

yes, it lists all triggers (`STANDARD`, `GROUP` and `MEMBER`), no need to tell it which ones I want.

> Can you give an example output? And consider adding an example playbook. It's not very clear which params you need in list mode.

I plan to add a comment in the docs, once I'll have time to write them :)
This is an example output:

```
"triggers": [
            {
                "actions": null, 
                "auto_disable": false, 
                "auto_enable": false, 
                "auto_resolve": false, 
                "auto_resolve_alerts": true, 
                "auto_resolve_match": "ALL", 
                "context": null, 
                "data_id_map": null, 
                "description": null, 
                "enabled": true, 
                "event_category": null, 
                "event_text": null, 
                "event_type": "ALERT", 
                "firing_match": "ALL", 
                "id": "test_group-002", 
                "member_of": null, 
                "name": "Test Group 01", 
                "severity": "HIGH", 
                "source": "_none_", 
                "tags": null, 
                "type": "GROUP"
            }, 
            {
                "actions": null, 
                "auto_disable": false, 
                "auto_enable": false, 
                "auto_resolve": true, 
                "auto_resolve_alerts": true, 
                "auto_resolve_match": "ALL", 
                "context": null, 
                "data_id_map": null, 
                "description": "Availability check trigger", 
                "enabled": true, 
                "event_category": null, 
                "event_text": null, 
                "event_type": "ALERT", 
                "firing_match": "ALL", 
                "id": "test-trigger-z", 
                "member_of": null, 
                "name": "Availability check trigger", 
                "severity": "HIGH", 
                "source": "_none_", 
                "tags": null, 
                "type": "STANDARD"
            }
        ]

```
> 
> Will/should this include associated conditions?
> 

IINM currently the API doesn't support this action

> Ideally, the output should be similar to something you can feed back into this module.
> For example might(?) want to reverse context.name and trigger_mode transformations you do in #9.
>  to merge as is and revisit after the group trigger format is settled...

I agree, but I think at the  moment we should try to focus on completing the MVP features

**Pull request merged**
