### PR TITLE
Add SSL Cert Verification support to the modules

### PR DESCRIPTION
**Pull request by dkorn**
SSL certificate verification is enabled by default.
To use a self-signed certificate pass the certificate file path using the ca_file_path option:
`ca_bundle_path: '/path/to/certfile'`

To ignore verifying the SSL certificate pass `verify_ssl: False`

### CODE REVIEW

**Comment by dkorn** [comment]
@cben @enoodle @simon3z @ivanhorvath please review

**Comment by simon3z** [comment]
cc @moolitayer

**Review by cben — APPROVED** [review]

**Comment by dkorn** [comment]
thanks @cben 
merging

**Comment by dkorn** [comment]
thanks @cben
merging

**Pull request merged**
