### PR TITLE
Add files required to create PyPi package

### PR DESCRIPTION
**Pull request by zgalor**
Add setup.py and change README to rst format.
license still missing.

### CODE REVIEW

**Comment by zgalor** [comment]
@dkorn please review

**Review by dkorn — APPROVED** [review]
@zgalor looks good. 
It seems reStructuredText has some good advantages over Markdown.

@cben can you review and give your 2 cents on this topic?

**Comment by cben** [comment]
rST LGTM.
It's not like PyPI makes it painless (http://inre.dundeemt.com/2014-05-04/pypi-vs-readme-rst-a-tale-of-frustration-and-unnecessary-binding/) but easier than the contortions needed for markdown...


@zgalor That blog post + some googling teaches about `setup.py check` which complains:
```
> python setup.py check --restructuredtext --strict --metadata
error in hawkular-alerts-module setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in hawkular/hawkular-client-python at /hawkular-client-python
```

**Comment by cben** [comment]
Also neat tip here: https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/#the-pypi-staging-server  — you can release to the staging pypi, verify everything worked, then release on real pypi.  More total work though.

**Comment by zgalor** [comment]
irrelevant

**Pull request closed without merging**
